#!/usr/bin/env bash

if [ -z "$SSH_AUTH_SOCK" ] ; then
	eval `ssh-agent -s`
	ssh-add
fi

/usr/bin/docker run -p 80:80 -p 443:443 -p 1883:1883 --volume /etc/localtime:/etc/localtime:ro --volumes-from datavidek --volume $SSH_AUTH_SOCK:/root/ssh-agent -e SSH_AUTH_SOCK=/root/ssh-agent -e EMAIL=example@gmail.com -e PASSWORD=secret -e DOMAIN=localhost -e WS=localhost -e RUNDECKP=secret -e ANSIBLE_USER=someuser -e HTTPS=true -e GITHUB_HOOK=8000 -e GITHUB_TOKEN=secret -e SECRET_TOKEN=secret -e GRAFANA=172.17.0.1:3000 -e MQTTP=secret videk
