#!/usr/bin/expect

set user [lindex $argv 0]
set pass [lindex $argv 1]

cd /var/lib/rundeck/bootstrap

spawn bash -c "java -jar rundeck-*.war --encryptpwd Jetty"

expect "Username (Optional, but necessary for Crypt encoding):"
send "$user\n"
expect "*Value To Encrypt (The text you want to encrypt):"
send "$pass\n"
interact